# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5b4c9e9483e13b163d2d9e2b046ad0df8e53f3964f50149a9da8fda3d62e4e57575aba3308783a85606b219c1d601ea1a9c65585629582a8713975e249e14ae

test:
  secret_key_base: 63fe48ed9656793d5457cbf7d4f0d5375d82200ce9b6e6cb38ebcaa5675f7efa27f78527ac34f12b1b9e70bde495b1fbfb139082e77db8abea410039467b11fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
